# Overcommit git hooks
# For a complete list of options that you can use to customize hooks, see:
# https://github.com/brigade/overcommit#configuration

PreCommit:
  HardTabs:
    enabled: true
  TrailingWhitespace:
    enabled: true
  YamlSyntax:
    enabled: true


PostCheckout:
  PipInstall:
    enabled: true
    description: 'Install pip dependencies'
    requires_files: true
    required_executable: 'pip'
    flags: ['install', '-r', 'requirements_dev.txt']
    include:
      - 'requirements/common.txt'
      - 'requirements/development.txt'
      - 'requirements/production.txt'
      - 'requirements_dev.txt'
      - 'requirements_test.txt'
      - 'requirements.txt'

PostMerge:
  PipInstall:
    enabled: true
    description: 'Install pip dependencies'
    requires_files: true
    required_executable: 'pip'
    flags: ['install', '-r', 'requirements_dev.txt']
    include:
      - 'requirements/common.txt'
      - 'requirements/development.txt'
      - 'requirements/production.txt'
      - 'requirements_dev.txt'
      - 'requirements_test.txt'
      - 'requirements.txt'

CommitMsg:
  HardTabs:
    enabled: true
  RussianNovel:
    enabled: true
