# Pre-Commit hooks
# See: https://pre-commit.com/hooks.html
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: check-ast
  - id: check-byte-order-marker
  - id: check-json
  - id: check-symlinks
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: flake8
  - id: fix-encoding-pragma
  - id: forbid-new-submodules
  - id: trailing-whitespace
  language_version: python3.6

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.4
  hooks:
  - id: isort

- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    language_version: python3.6
