# https://travis-ci.org/cloudsmith-io/cloudsmith-cli
dist: trusty
sudo: false
language: python

python:
  - "3.5"

env:
  - TOXENV=py27
  - TOXENV=py35
  - TOXENV=flake8

matrix:
  fast_finish: true
  include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.5"
      env: TOXENV=py35

install:
  - pip install --upgrade pip setuptools wheel

script:
  - tox

notifications:
  email:
    on_failure: always
    on_success: change
