# https://travis-ci.org/cloudsmith-io/cloudsmith-cli
dist: trusty
sudo: false
language: python

matrix:
  fast_finish: true
  include:
    - python: 2.7
      env:
        - TOXENV=py27
    - python: 3.5
      env:
        - TOXENV=py35
    - env:
        - TOXENV=flake8
    - env:
        - TOXENV=pylint
    - env:
        - TOXENV=isort

install:
  - pip install --upgrade pip setuptools wheel
  - pip install tox codecov

script:
  - tox

after_success:
  - codecov

notifications:
  email:
    on_failure: always
    on_success: change
