# https://travis-ci.org/cloudsmith-io/cloudsmith-cli
dist: trusty
sudo: false
language: python

env:
  - TOXENV=py27
  - TOXENV=py35
  - TOXENV=flake8
  - TOXENV=pylint
  - TOXENV=isort

matrix:
  fast_finish: true

install:
  - pip install --upgrade pip setuptools wheel

script:
  - tox

after_success:
  - codecov

notifications:
  email:
    on_failure: always
    on_success: change
